### ISSUE TITLE
Reset state progress bar?

### ISSUE THREAD

**Issue by philipphager** [kofigyan/StateProgressBar#7] opened 2017-02-09 20:49 UTC
I wanted to reset the progress bar in the same view if the corresponding action was restarted, but after all states have been checked, I'm not able to reset the states to its initial state. Is there any way to reuse the progress bar after it completed once?

**Comment by kofigyan** [comment] 2017-02-09 23:22
Hi @philipphager , the question looks multi-faceted so l will try and breakdown the answer. 

> I wanted to reset the progress bar in the same view if the corresponding action was restarted -

_You can do this by setting the current state dynamically. ie. setCurrentStateNumber(StateNumber)_

> but after all states have been checked, 

_You can equally do this by setting it dynamically , ie. setAllStatesCompleted(boolean)_

> I'm not able to reset the states to its initial state

_You can do this by setting the current state dynamically to ONE. ie. setCurrentStateNumber(StateNumber.ONE)_

> Is there any way to reuse the progress bar after it completed once?

_Yes as shown in the above answers._

Let me know if your question is adequately answered or otherwise. You can equally check out the wiki page for further documentation.

**Comment by philipphager** [comment] 2017-02-10 09:09
Thank you for your answer!
But when I call the following to reset my progress bar:
```
stateProgressBar.setAllStatesCompleted(false);
stateProgressBar.setCurrentStateNumber(StateProgressBar.StateNumber.ONE);
```
 
I get this strange visually inconsistent state:

<img width="274" alt="bildschirmfoto 2017-02-10 um 10 00 39" src="https://cloud.githubusercontent.com/assets/9155371/22820850/d80e0bf4-ef78-11e6-8533-61a08001eb98.png">

This was the actual initial state I want the progress bar to reset to:
<img width="267" alt="bildschirmfoto 2017-02-10 um 10 08 33" src="https://cloud.githubusercontent.com/assets/9155371/22820903/0a6966f2-ef79-11e6-8a02-95992a2e6b8e.png">

**Comment by kofigyan** [comment] 2017-02-10 09:26
Looks like you are using the library wrongly hence the inconsistent result. 
To attain the desired result just use this : 
 stateProgressBar.setCurrentStateNumber(StateProgressBar.StateNumber.ONE);

**Comment by kofigyan** [comment] 2017-02-10 10:15
@philipphager Let me know how it went when you are done. If you are still not getting the desired result then you might have to share the content of your xml and .java files with me to further understand how you are using the library. The wiki page also has very good guide on using the library.

**Comment by Fredrib** [comment] 2017-02-10 10:52
I got a similar problem trying to reset the bar to its first stage, although I didn't have a problem going back from third stage to second stage, for instance. If I've tried to go back from second stage to first stage, the joining line of this two stages don't get erased. I've looked into the code and find out a solution making a small change and I have submit a PR for this. You might look into the PR and see if that make sense to you.

**Comment by kofigyan** [comment] 2017-02-10 11:32
@Fredrib Sorry for the late in reply. I have decided to look into the PR this weekend and give you a feedback. On this issue: 

>  If I've tried to go back from second stage to first stage, the joining line of this two stages don't get erased.

_There is a real world example in the sample code labelled Usage(Real world example) where you can move from second stage to first stage. If your use case is not different from this example then you can look into it. This is also available on the Google PlayStore  _  [StateProgress Link to PlayStore](https://play.google.com/store/apps/details?id=com.kofigyan.stateprogressbarsample)

If the above solution does not meet your use case then please share with me the particular use case. It could be further explanation,sample codes or screenshots. This will help me to reproduce the case and apply the solution in the PR to it.  And thank you for contributing to this project.

**Comment by kofigyan** [comment] 2017-02-10 14:29
@philipphager  and @Fredrib  I have examined the issue raised deeply and is clear the library does not have provision for resetting the stateprogressbar after it has completed. I will add this functionality either this evening or latest by tomorrow. Thanks to @Fredrib for your PR. I will update everyone on this in version 0.03.

**Comment by Fredrib** [comment] 2017-02-10 15:01
@kofigyan sorry I couldn't get back to you in time, but I believe you already reproduce the bug. Looking forward to your version update. Thanks and keep up the good work!

**Comment by philipphager** [comment] 2017-02-10 15:32
Thank you for the good work and the fast replies! Looking forward to the update!

**Comment by kofigyan** [comment] 2017-02-13 09:10
@philipphager and @Fredrib StateProgressBar version 0.0.3 is now officially released with the issue resolved. @Fredrib l have accepted your pull request and merged with the master branch. Thank you all for your contributions.

**Comment by philipphager** [comment] 2017-02-13 09:44
Thank you very much @kofigyan! For me, it works like a charm! 👍

**Comment by kofigyan** [comment] 2017-02-13 09:53
@philipphager  l appreciate your positive feedback.I will keep on working on additional features to further enrich the library.

**Closed as completed** 2017-02-13 16:31 UTC

**Comment by kofigyan** [comment] 2018-06-22 10:48
Hi @philipphager and @Fredrib , would you mind writing a short testimonial of your impression using my work and collaborating with me. This is for my application for a master's degree program in computer science. Thanks.
