### ISSUE TITLE
Issue while setting Current state number dynamically

### ISSUE THREAD

**Issue by amitsri20** [kofigyan/StateProgressBar#2] opened 2017-01-02 14:04 UTC
I am trying to set current state number dynamically but it is not showing correct result while when I set in XML file it works fine.

I have used 
stateProgressBar.setCurrentStateNumber(StateProgressBar.StateNumber.TWO);

after removing app:spb_currentStateNumber="two" from XML file.

See the result below current description is showing correctly but progress line is going to opposite direction.

![issue](https://cloud.githubusercontent.com/assets/4771159/21590499/55528fec-d122-11e6-89d8-a6234160a3cc.PNG)

**Comment by kofigyan** [comment] 2017-01-03 09:32
Hi Amit, I have tried to reproduce similar result with all possible scenarios but all work fine on multiple devices. Please can you show elaborate codes ? Are you testing in an emulator or specific device ? Does it occur after certain action e.g. screen orientation change etc ? Any extra information will be useful.

**Comment by amitsri20** [comment] 2017-01-14 09:43
Hi, I am sharing the video of my scenario.
https://drive.google.com/file/d/0B97xPWRVxZSPRzNqS3JSOFdFVTg/view?usp=sharing

As you will see in the video, it does not happen every time but if I am opening activity with status view multiple times few times I face the problem.

Please suggest.

**Comment by amitsri20** [comment] 2017-01-20 10:47
Hi,

One thing I figured out about this is that it only happens when the animation is set to true.

**Comment by kofigyan** [comment] 2017-01-20 11:00
Thank you Amit for the extra information. Found the possible reason for
this anomaly. Will work on it over the weekend and update you thereafter.

**Comment by kofigyan** [comment] 2017-01-31 01:01
Hi Amit, I believe the issue is resolved now.  I am adding the other feature requests by the various users to form version 0.0.2 . You can download the stateprogressbar library(or copy the classes together with the asset and values folders contents)  from the master branch into your project for now and test. Your feedback will be appreciated.

**Comment by amitsri20** [comment] 2017-01-31 04:04
Sure, I will test and tell you back.

Thanks

**Comment by apaul10** [comment] 2017-01-31 04:50
Hello,

I am realizing the same issue, when using progressBar inside Listview/RecyclerView, when one item is being set, all items are being updated with the same value.

**Comment by kofigyan** [comment] 2017-01-31 06:06
Hi @apaul10 ,
      I believe the issue raised by @amitsri20 is resolved and will be available in version 0.0.2 soon. You can download the stateprogressbar library(or copy the classes together with the asset and values folders contents) from the master branch into your project for now.

**Comment by kofigyan** [comment] 2017-02-04 11:33
Hi @amitsri20 and @apaul10 ,
   Version 0.0.2 of the library is now officially released. You can now use this version as it solves this issue.

**Comment by apaul10** [comment] 2017-02-05 12:55
@kofigyan Thanks much

**Comment by kofigyan** [comment] 2017-02-05 13:08
@apaul10  You are welcome.

**Comment by amitsri20** [comment] 2017-02-06 06:51
Great job will check the latest one..thanks a lot for creating such a good
library.

**Comment by kofigyan** [comment] 2017-02-06 08:51
You are welcome Amit.

**Comment by kofigyan** [comment] 2017-02-06 12:22
@amitsri20  l will be waiting for your immediate feedback to close this issue.

**Closed as completed** 2017-02-14 15:23 UTC
